baseurl = "https://foncubierta.com"
title = "Ezequiel Foncubierta"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "efoncubierta"

[params]
  author = "Ezequiel Foncubierta"
  info = "Software engineer, aspiring astrophysicist and mountain runner"
  description = "Ezequiel Foncubierta website"
  keywords = "blog,developer,personal,cloud,infrastructure,aws,azure,kubernetes"
  avatarurl = "images/avatar.jpg"
  gravatar = "ezequiel@foncubierta.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

#  customCSS = ["css/custom.css"]
#  customSCSS = ["scss/custom.scss"]
#  customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/efoncubierta"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/twitter/EzeFoncubierta"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 3
  url = "https://instagram.com/ultrafoncu"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 4
  url = "https://mastodon.online/@eze"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 5
  url = "https://www.linkedin.com/in/efoncubierta/"
[[params.social]]
  name = "Principia Machina"
  icon = "fa fa-newspaper fa-2x"
  weight = 5
  url = "https://principiamachina.substack.com"

# Menu links
[[menu.main]]
  name = "Principia Machina"
  weight = 1
  url  = "https://principiamachina.substack.com"